In [ ]:
import pandas as pd

In [5]:
data = pd.read_excel("../src/chocolate_sales.xlsx")

In [6]:
data

,Sales_Person,Country,Product,Date,Amount,Boxes_Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-04-01 00:00:00,5320.00,180
1,Van Tuxwell,India,85% Dark Bars,2022-01-08 00:00:00,7896.00,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07 00:00:00,4501.00,91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,12726.00,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,13685.00,184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17/05/2024,5303.58,354
3278,Jehu Rudeforth,USA,White Choc,2024-07-06 00:00:00,7339.32,121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26/07/2024,616.09,238
3280,Dotty Strutley,India,Eclairs,28/07/2024,2504.62,397
3281,Karlen McCaffrey,India,70% Dark Bites,23/05/2024,5915.87,355

In [7]:
data['Date'] = pd.to_datetime(data['Date'])

In [8]:
data

,Sales_Person,Country,Product,Date,Amount,Boxes_Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-04-01,5320.00,180
1,Van Tuxwell,India,85% Dark Bars,2022-01-08,7896.00,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.00,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.00,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.00,184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,2024-05-17,5303.58,354
3278,Jehu Rudeforth,USA,White Choc,2024-07-06,7339.32,121
3279,Ches Bonnell,Canada,Organic Choco Syrup,2024-07-26,616.09,238
3280,Dotty Strutley,India,Eclairs,2024-07-28,2504.62,397
3281,Karlen McCaffrey,India,70% Dark Bites,2024-05-23,5915.87,355

In [9]:
data.to_excel("../src/cholocate_sales_cleaned.xlsx",index=False)